apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build
spec:
  params:
    - name: REPO_URL
      type: string
  steps:
    - name: clone-repo
      image: node
      script: |
        git clone $(params.REPO_URL) /workspace/source
    - name: npm-install
      image: node
      workingDir: /workspace/source
      script: |
        npm install
    - name: npm-test
      image: node
      workingDir: /workspace/source
      script: |
        npm test