apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
spec:
  params:
    - name: NAMESPACE
      type: string
    - name: IMAGE
      type: string
    - name: REPO_URL
      type: string
  steps:
    - name: clone-repo
      image: node
      script: |
        git clone $(params.REPO_URL) /workspace/source
    - name: apply-deployment
      image: lachlanevenson/k8s-kubectl
      script: |
        kubectl apply -f /workspace/source/tekton/k8s/nginx-deployment.yml
    - name: update-image
      image: lachlanevenson/k8s-kubectl
      script: |
        kubectl set image deployment/nginx-deployment nginx=$(params.IMAGE) -n=$(params.NAMESPACE)