apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: Intern
  namespace: dev
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "deployments"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: InternBinding
  namespace: dev
subjects:
- kind: User
  name: Jules
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: Intern
  apiGroup: rbac.authorization.k8s.io